### ISSUE TITLE
Unintuitive behavior in existing window

### ISSUE THREAD

**Issue by xeruf** [weinshec/vim-dictcc#3]
When calling `:Dict` and calling it again without closing the buffer in between, it clears the buffer, spits out a warning and creates a new one:

    W10: Warning: Changing a readonly file

I use neovim in case that makes a difference.

This can end up like this after 4 invocations:
![image](https://user-images.githubusercontent.com/13354331/133612109-a1f0327c-1c80-4969-872b-1e0b15be8b05.png)

**Comment by IngoMeyer441** [comment]
Should be fixed with PR #4.

**Comment by weinshec** [comment]
Fixed with #4 and #5 
(Thx @IngoMeyer441)
